# Site settings
title:    Nhu Nguyen
email:    qnguyen47@gatech.edu
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://qnguyen29.github.io/nhunguyen.github.io/" # the base hostname & protocol for your site
# url: "https://qnguyen29.github.io" # the base hostname & protocol for your site

linkedin_username: Nhu Nguyen
github_username: /qnguyen29

# Build settings
markdown: kramdown
